interface CodeTemplate {
  files: Record<string, string>;
  instructions: string;
}

export class AIService {
  private static instance: AIService;
  private apiKey: string = '';

  private constructor() {}

  public static getInstance(): AIService {
    if (!AIService.instance) {
      AIService.instance = new AIService();
    }
    return AIService.instance;
  }

  setApiKey(key: string) {
    this.apiKey = key;
  }

  private getHelloWorldTemplate(): CodeTemplate {
    return {
      files: {
        'src/components/HelloWorld.jsx': `import React from 'react';

export const HelloWorld = ({ message = 'Hello World!' }) => {
  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
    }}>
      <div style={{
        background: 'white',
        padding: '40px',
        borderRadius: '20px',
        boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
        textAlign: 'center',
        transform: 'scale(1)',
        transition: 'transform 0.3s ease'
      }}
      onMouseEnter={(e) => e.currentTarget.style.transform = 'scale(1.05)'}
      onMouseLeave={(e) => e.currentTarget.style.transform = 'scale(1)'}
      >
        <h1 style={{
          fontSize: '3rem',
          fontWeight: 'bold',
          color: '#333',
          marginBottom: '20px',
          animation: 'fadeIn 1s ease-in'
        }}>
          {message}
        </h1>
        <p style={{ fontSize: '1.2rem', color: '#666', marginBottom: '30px' }}>
          Generated by R3alm Dev AI
        </p>
        <div style={{ display: 'flex', justifyContent: 'center', gap: '10px', flexWrap: 'wrap' }}>
          <span style={{
            display: 'inline-block',
            padding: '10px 20px',
            background: '#dbeafe',
            color: '#1e40af',
            fontSize: '0.9rem',
            borderRadius: '20px',
            fontWeight: '500'
          }}>React</span>
          <span style={{
            display: 'inline-block',
            padding: '10px 20px',
            background: '#fce7f3',
            color: '#be185d',
            fontSize: '0.9rem',
            borderRadius: '20px',
            fontWeight: '500'
          }}>JavaScript</span>
          <span style={{
            display: 'inline-block',
            padding: '10px 20px',
            background: '#dcfce7',
            color: '#166534',
            fontSize: '0.9rem',
            borderRadius: '20px',
            fontWeight: '500'
          }}>Vite</span>
        </div>
      </div>
    </div>
  );
};
`,
        'src/App.jsx': `import React from 'react';
import { HelloWorld } from './components/HelloWorld';

function App() {
  return <HelloWorld message="Welcome to R3alm Dev!" />;
}

export default App;`
      },
      instructions: 'Created a beautiful Hello World component with React. Features a gradient background, modern card design with shadow effects, and smooth hover animations.'
    };
  }

  private getTodoListTemplate(): CodeTemplate {
    return {
      files: {
        'src/components/TodoList.jsx': `import React, { useState } from 'react';

export const TodoList = () => {
  const [todos, setTodos] = useState([
    { id: 1, text: 'Learn React', completed: true },
    { id: 2, text: 'Build an app', completed: false },
    { id: 3, text: 'Deploy to production', completed: false }
  ]);
  const [input, setInput] = useState('');

  const addTodo = () => {
    if (input.trim()) {
      setTodos([...todos, { id: Date.now(), text: input, completed: false }]);
      setInput('');
    }
  };

  const toggleTodo = (id) => {
    setTodos(todos.map(todo =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    ));
  };

  const deleteTodo = (id) => {
    setTodos(todos.filter(todo => todo.id !== id));
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') addTodo();
  };

  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px',
      fontFamily: 'system-ui, sans-serif'
    }}>
      <div style={{ width: '100%', maxWidth: '500px' }}>
        <div style={{
          background: 'white',
          borderRadius: '20px',
          boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
          overflow: 'hidden'
        }}>
          <div style={{
            background: 'linear-gradient(135deg, #3b82f6 0%, #06b6d4 100%)',
            padding: '30px',
            color: 'white'
          }}>
            <h1 style={{ fontSize: '2rem', fontWeight: 'bold', margin: '0 0 8px 0' }}>
              My Tasks
            </h1>
            <p style={{ margin: 0, opacity: 0.9 }}>Stay organized and productive</p>
          </div>

          <div style={{ padding: '30px' }}>
            <div style={{ display: 'flex', gap: '10px', marginBottom: '25px' }}>
              <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder="Add a new task..."
                style={{
                  flex: 1,
                  padding: '12px 16px',
                  border: '2px solid #e5e7eb',
                  borderRadius: '10px',
                  fontSize: '16px',
                  outline: 'none'
                }}
                onFocus={(e) => e.target.style.borderColor = '#3b82f6'}
                onBlur={(e) => e.target.style.borderColor = '#e5e7eb'}
              />
              <button
                onClick={addTodo}
                style={{
                  padding: '12px 20px',
                  background: '#3b82f6',
                  color: 'white',
                  border: 'none',
                  borderRadius: '10px',
                  fontSize: '16px',
                  cursor: 'pointer',
                  fontWeight: '600'
                }}
                onMouseEnter={(e) => e.target.style.background = '#2563eb'}
                onMouseLeave={(e) => e.target.style.background = '#3b82f6'}
              >
                + Add
              </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {todos.map((todo) => (
                <div
                  key={todo.id}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px',
                    padding: '15px',
                    background: '#f9fafb',
                    borderRadius: '10px',
                    transition: 'background 0.2s'
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.background = '#f3f4f6'}
                  onMouseLeave={(e) => e.currentTarget.style.background = '#f9fafb'}
                >
                  <button
                    onClick={() => toggleTodo(todo.id)}
                    style={{
                      width: '24px',
                      height: '24px',
                      borderRadius: '6px',
                      border: todo.completed ? '2px solid #3b82f6' : '2px solid #d1d5db',
                      background: todo.completed ? '#3b82f6' : 'transparent',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      transition: 'all 0.2s',
                      flexShrink: 0
                    }}
                  >
                    {todo.completed && (
                      <span style={{ color: 'white', fontSize: '14px' }}>✓</span>
                    )}
                  </button>
                  <span style={{
                    flex: 1,
                    color: todo.completed ? '#9ca3af' : '#374151',
                    textDecoration: todo.completed ? 'line-through' : 'none'
                  }}>
                    {todo.text}
                  </span>
                  <button
                    onClick={() => deleteTodo(todo.id)}
                    style={{
                      padding: '6px 10px',
                      background: 'transparent',
                      color: '#ef4444',
                      border: 'none',
                      borderRadius: '6px',
                      cursor: 'pointer',
                      fontSize: '18px'
                    }}
                    onMouseEnter={(e) => e.target.style.background = '#fee2e2'}
                    onMouseLeave={(e) => e.target.style.background = 'transparent'}
                  >
                    ×
                  </button>
                </div>
              ))}
            </div>

            {todos.length === 0 && (
              <div style={{
                textAlign: 'center',
                padding: '40px',
                color: '#9ca3af'
              }}>
                <p>No tasks yet. Add one to get started!</p>
              </div>
            )}

            <div style={{
              marginTop: '20px',
              paddingTop: '20px',
              borderTop: '1px solid #e5e7eb',
              textAlign: 'center',
              fontSize: '14px',
              color: '#6b7280'
            }}>
              {todos.filter(t => !t.completed).length} of {todos.length} tasks remaining
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
`,
        'src/App.jsx': `import React from 'react';
import { TodoList } from './components/TodoList';

function App() {
  return <TodoList />;
}

export default App;`
      },
      instructions: 'Created a fully functional Todo List component with add, complete, and delete functionality. Features a modern gradient header, smooth animations, and responsive design.'
    };
  }

  private getContactFormTemplate(): CodeTemplate {
    return {
      files: {
        'src/components/ContactForm.jsx': `import React, { useState } from 'react';

export const ContactForm = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    message: ''
  });
  const [errors, setErrors] = useState({});
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const validateEmail = (email) => {
    return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email);
  };

  const validate = () => {
    const newErrors = {};

    if (!formData.name.trim()) {
      newErrors.name = 'Name is required';
    }

    if (!formData.email.trim()) {
      newErrors.email = 'Email is required';
    } else if (!validateEmail(formData.email)) {
      newErrors.email = 'Please enter a valid email';
    }

    if (!formData.message.trim()) {
      newErrors.message = 'Message is required';
    } else if (formData.message.length < 10) {
      newErrors.message = 'Message must be at least 10 characters';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validate()) return;

    setIsLoading(true);
    await new Promise(resolve => setTimeout(resolve, 1500));

    setIsLoading(false);
    setIsSubmitted(true);
    setFormData({ name: '', email: '', message: '' });

    setTimeout(() => setIsSubmitted(false), 5000);
  };

  const handleChange = (field) => (e) => {
    setFormData({ ...formData, [field]: e.target.value });
    if (errors[field]) {
      setErrors({ ...errors, [field]: undefined });
    }
  };

  if (isSubmitted) {
    return (
      <div style={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px',
        fontFamily: 'system-ui, sans-serif'
      }}>
        <div style={{
          background: 'white',
          borderRadius: '20px',
          boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
          padding: '50px',
          textAlign: 'center',
          maxWidth: '400px'
        }}>
          <div style={{
            width: '80px',
            height: '80px',
            background: '#d1fae5',
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 20px'
          }}>
            <span style={{ fontSize: '40px', color: '#10b981' }}>✓</span>
          </div>
          <h2 style={{ fontSize: '2rem', fontWeight: 'bold', color: '#333', margin: '0 0 10px 0' }}>
            Message Sent!
          </h2>
          <p style={{ color: '#666', margin: 0 }}>
            Thank you for contacting us. We'll get back to you soon.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px',
      fontFamily: 'system-ui, sans-serif'
    }}>
      <div style={{ width: '100%', maxWidth: '500px' }}>
        <div style={{
          background: 'white',
          borderRadius: '20px',
          boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
          overflow: 'hidden'
        }}>
          <div style={{
            background: 'linear-gradient(135deg, #2563eb 0%, #06b6d4 100%)',
            padding: '40px',
            textAlign: 'center',
            color: 'white'
          }}>
            <div style={{ fontSize: '3rem', marginBottom: '15px' }}>✉️</div>
            <h1 style={{ fontSize: '2rem', fontWeight: 'bold', margin: '0 0 10px 0' }}>
              Get in Touch
            </h1>
            <p style={{ margin: 0, opacity: 0.9 }}>We'd love to hear from you</p>
          </div>

          <form onSubmit={handleSubmit} style={{ padding: '40px' }}>
            <div style={{ marginBottom: '25px' }}>
              <label style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '14px',
                fontWeight: '500',
                color: '#374151',
                marginBottom: '8px'
              }}>
                <span>👤</span>
                <span>Name</span>
              </label>
              <input
                type="text"
                value={formData.name}
                onChange={handleChange('name')}
                placeholder="John Doe"
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  border: \`2px solid \${errors.name ? '#ef4444' : '#e5e7eb'}\`,
                  borderRadius: '10px',
                  fontSize: '16px',
                  outline: 'none',
                  boxSizing: 'border-box'
                }}
                onFocus={(e) => !errors.name && (e.target.style.borderColor = '#3b82f6')}
                onBlur={(e) => !errors.name && (e.target.style.borderColor = '#e5e7eb')}
              />
              {errors.name && (
                <p style={{ color: '#ef4444', fontSize: '14px', marginTop: '5px', margin: '5px 0 0 0' }}>
                  {errors.name}
                </p>
              )}
            </div>

            <div style={{ marginBottom: '25px' }}>
              <label style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '14px',
                fontWeight: '500',
                color: '#374151',
                marginBottom: '8px'
              }}>
                <span>📧</span>
                <span>Email</span>
              </label>
              <input
                type="email"
                value={formData.email}
                onChange={handleChange('email')}
                placeholder="john@example.com"
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  border: \`2px solid \${errors.email ? '#ef4444' : '#e5e7eb'}\`,
                  borderRadius: '10px',
                  fontSize: '16px',
                  outline: 'none',
                  boxSizing: 'border-box'
                }}
                onFocus={(e) => !errors.email && (e.target.style.borderColor = '#3b82f6')}
                onBlur={(e) => !errors.email && (e.target.style.borderColor = '#e5e7eb')}
              />
              {errors.email && (
                <p style={{ color: '#ef4444', fontSize: '14px', marginTop: '5px', margin: '5px 0 0 0' }}>
                  {errors.email}
                </p>
              )}
            </div>

            <div style={{ marginBottom: '25px' }}>
              <label style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '14px',
                fontWeight: '500',
                color: '#374151',
                marginBottom: '8px'
              }}>
                <span>💬</span>
                <span>Message</span>
              </label>
              <textarea
                value={formData.message}
                onChange={handleChange('message')}
                rows={4}
                placeholder="Tell us what's on your mind..."
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  border: \`2px solid \${errors.message ? '#ef4444' : '#e5e7eb'}\`,
                  borderRadius: '10px',
                  fontSize: '16px',
                  outline: 'none',
                  resize: 'none',
                  fontFamily: 'inherit',
                  boxSizing: 'border-box'
                }}
                onFocus={(e) => !errors.message && (e.target.style.borderColor = '#3b82f6')}
                onBlur={(e) => !errors.message && (e.target.style.borderColor = '#e5e7eb')}
              />
              {errors.message && (
                <p style={{ color: '#ef4444', fontSize: '14px', marginTop: '5px', margin: '5px 0 0 0' }}>
                  {errors.message}
                </p>
              )}
            </div>

            <button
              type="submit"
              disabled={isLoading}
              style={{
                width: '100%',
                background: isLoading ? '#9ca3af' : 'linear-gradient(135deg, #2563eb 0%, #06b6d4 100%)',
                color: 'white',
                fontWeight: '600',
                padding: '14px',
                border: 'none',
                borderRadius: '10px',
                fontSize: '16px',
                cursor: isLoading ? 'not-allowed' : 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '10px',
                transition: 'transform 0.2s'
              }}
              onMouseEnter={(e) => !isLoading && (e.target.style.transform = 'scale(1.02)')}
              onMouseLeave={(e) => !isLoading && (e.target.style.transform = 'scale(1)')}
            >
              {isLoading ? (
                <>
                  <div style={{
                    width: '20px',
                    height: '20px',
                    border: '2px solid white',
                    borderTopColor: 'transparent',
                    borderRadius: '50%',
                    animation: 'spin 1s linear infinite'
                  }} />
                  <span>Sending...</span>
                </>
              ) : (
                <>
                  <span>✉️</span>
                  <span>Send Message</span>
                </>
              )}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};
`,
        'src/App.jsx': `import React from 'react';
import { ContactForm } from './components/ContactForm';

function App() {
  return <ContactForm />;
}

export default App;`
      },
      instructions: 'Created a fully functional contact form with comprehensive validation (name, email format, message length). Features real-time error display, loading states, success confirmation, and a beautiful gradient design with smooth animations.'
    };
  }

  private getTemplate(prompt: string): CodeTemplate | null {
    const lowerPrompt = prompt.toLowerCase();

    if (lowerPrompt.includes('hello world')) {
      return this.getHelloWorldTemplate();
    }

    if (lowerPrompt.includes('todo')) {
      return this.getTodoListTemplate();
    }

    if (lowerPrompt.includes('contact form') || lowerPrompt.includes('form')) {
      return this.getContactFormTemplate();
    }

    return null;
  }

  async generateCode(prompt: string, context?: any): Promise<{ files: Record<string, string>; instructions: string }> {
    await new Promise(resolve => setTimeout(resolve, 2000));

    const template = this.getTemplate(prompt);
    if (template) {
      return template;
    }

    return {
      files: {
        'src/components/GeneratedComponent.jsx': `import React from 'react';

export const GeneratedComponent = () => {
  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #1f2937 0%, #111827 100%)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px',
      fontFamily: 'system-ui, sans-serif'
    }}>
      <div style={{
        background: 'white',
        borderRadius: '15px',
        boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
        padding: '40px',
        maxWidth: '500px',
        width: '100%'
      }}>
        <h2 style={{
          fontSize: '1.75rem',
          fontWeight: 'bold',
          color: '#333',
          marginBottom: '15px'
        }}>
          Generated Component
        </h2>
        <p style={{ color: '#666', marginBottom: '25px' }}>
          This is a placeholder component. Try one of the suggested commands for better results!
        </p>
        <div style={{
          background: '#dbeafe',
          border: '1px solid #93c5fd',
          borderRadius: '10px',
          padding: '20px'
        }}>
          <p style={{
            fontSize: '14px',
            color: '#1e40af',
            margin: 0
          }}>
            <strong>Try:</strong> "Create a Hello World React component" or "Create a todo list component"
          </p>
        </div>
      </div>
    </div>
  );
};
`,
        'src/App.jsx': `import React from 'react';
import { GeneratedComponent } from './components/GeneratedComponent';

function App() {
  return <GeneratedComponent />;
}

export default App;`
      },
      instructions: 'Generated a basic component structure. For better results, try using one of the suggested commands like "Create a Hello World React component", "Create a todo list component", or "Create a contact form with validation".'
    };
  }

  async getCompletions(code: string, position: { line: number; column: number }): Promise<string[]> {
    await new Promise(resolve => setTimeout(resolve, 300));

    return [
      'useState',
      'useEffect',
      'useCallback',
      'useMemo',
      'className',
      'onClick',
      'onChange'
    ];
  }
}

export const aiService = AIService.getInstance();
